apiVersion: v1
kind: Pod
metadata:
  name: database-pod
spec: 
  containers:
    - name: database-container
      image: mysql
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: AWS
        - name: MYSQL_USER
          value: devops
        - name: MYSQL_PASSWORD
          value: devops@123