apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: my-main-container
      image: nginx:1.29
      ports:
        - containerPort: 80
  ephemeralContainers:
    - name: mydebug-container
      image: busybox
      stdin: true
      targetContainerName: my-main-container
      tty: true
