apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
spec:
  containers:
    - name: my-main-container
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP
  initContainers:  
    - name: testing-purpose-1
      image: alpine
      command:
        - sleep
        - "5s"
    - name: testing-purpose-2
      image: alpine
      command:
        - sleep
        - "5s"