apiVersion: v1
kind: Service
metadata:
  name: mydemo-service
  namespace: prod
  labels:
    app: test-Env
spec:
  selector:
    app: dev   
  ports:
    - name: http
      port: 80          
      targetPort: 80    
  type: NodePort        
